Repository NOW-SOPT-APP2-KAKAOBANK/KAKAOBANK-Android, pull requests merged in 2024-05, with the labels that each got.

#5 [CHORE/#4] : Font 변수명 변경
  app/src/main/res/values/textAppearances.xml
Labels: 🛠️ [CHORE], 🐦 언지

#7 [MOD/#6] : textAppearances 폰트 속성 수정
  app/src/main/res/values/textAppearances.xml
Labels: ✅ [MOD], 🐦 언지

#12 [UI/#8] Home view UI 작업
  app/src/main/java/com/sopt/kakaobank/presentation/MainActivity.kt
  app/src/main/java/com/sopt/kakaobank/presentation/home/HomeFragment.kt
  app/src/main/java/com/sopt/kakaobank/presentation/home/HomeItem.kt
  app/src/main/java/com/sopt/kakaobank/presentation/home/HomeItemAdapter.kt
  app/src/main/java/com/sopt/kakaobank/presentation/home/HomeRecyclerViewItemDecorator.kt
  app/src/main/java/com/sopt/kakaobank/presentation/home/HomeViewModel.kt
  app/src/main/res/color/nav_item_color_state.xml
  app/src/main/res/drawable-mdpi/ic_bank_book1_logo.png
  app/src/main/res/drawable-mdpi/ic_bank_book3_logo.png
  app/src/main/res/drawable-mdpi/ic_card_ad.png
  app/src/main/res/drawable-mdpi/ic_compare.png
  app/src/main/res/drawable-mdpi/ic_couphone.png
  app/src/main/res/drawable-mdpi/ic_lion_31.png
  app/src/main/res/drawable-mdpi/ic_pig.png
  app/src/main/res/drawable-xhdpi/ic_bank_book1_logo_2x.png
  app/src/main/res/drawable-xhdpi/ic_bank_book3_logo_2x.png
  app/src/main/res/drawable-xhdpi/ic_card_ad_2x.png
  app/src/main/res/drawable-xhdpi/ic_compare_2x.png
  app/src/main/res/drawable-xhdpi/ic_couphone_2x.png
  app/src/main/res/drawable-xhdpi/ic_lion_31_2x.png
  app/src/main/res/drawable-xhdpi/ic_pig_2x.png
  app/src/main/res/drawable-xxhdpi/ic_bank_book1_logo_3x.png
  app/src/main/res/drawable-xxhdpi/ic_bank_book3_logo_3x.png
  app/src/main/res/drawable-xxhdpi/ic_card_ad_3x.png
  app/src/main/res/drawable-xxhdpi/ic_compare_3x.png
  app/src/main/res/drawable-xxhdpi/ic_couphone_3x.png
  app/src/main/res/drawable-xxhdpi/ic_lion_31_3x.png
  app/src/main/res/drawable-xxhdpi/ic_pig_3x.png
  app/src/main/res/drawable/ic_btn_cancel.xml
  app/src/main/res/drawable/ic_btn_leading.xml
  app/src/main/res/drawable/ic_btn_menu.xml
  app/src/main/res/drawable/ic_btn_more.xml
  app/src/main/res/drawable/ic_btn_my_bank.xml
  app/src/main/res/drawable/ic_btn_my_page.xml
  app/src/main/res/drawable/ic_btn_notification.xml
  app/src/main/res/drawable/ic_btn_plus.xml
  app/src/main/res/drawable/ic_profile.xml
  app/src/main/res/drawable/ic_star.xml
  app/src/main/res/drawable/shape_blue0_fill_15_rect.xml
  app/src/main/res/drawable/shape_blue1_fill_20_rect.xml
  app/src/main/res/drawable/shape_blue3_fill_20_rect.xml
  app/src/main/res/drawable/shape_darkgray0_fill_15_rect.xml
  app/src/main/res/drawable/shape_darkgray0_fill_50_rect.xml
  app/src/main/res/drawable/shape_main_fill_15_rect.xml
  app/src/main/res/drawable/shape_pink0_fill_15_rect.xml
  app/src/main/res/drawable/shape_yellow0_fill_20_rect.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/item_bank_book1.xml
  app/src/main/res/layout/item_bank_book2.xml
  app/src/main/res/layout/item_bank_book3.xml
  app/src/main/res/layout/item_check_limit.xml
  app/src/main/res/layout/item_couphone_buy_sell.xml
  app/src/main/res/layout/item_credit_loan_compare.xml
  app/src/main/res/layout/item_everyday_pin_money.xml
  app/src/main/res/layout/item_joint_account.xml
  app/src/main/res/layout/item_one_month_saving.xml
  app/src/main/res/layout/item_plus.xml
  app/src/main/res/menu/menu_home.xml
  app/src/main/res/values/strings.xml
Labels: 💟 [UI], 🐣 윤서

#10 [UI/#9] : History view UI 작업
  app/src/main/java/com/sopt/kakaobank/data/dto/response/History.kt
  app/src/main/java/com/sopt/kakaobank/presentation/history/HistoryAdapter.kt
  app/src/main/java/com/sopt/kakaobank/presentation/history/HistoryFragment.kt
  app/src/main/java/com/sopt/kakaobank/presentation/history/HistoryViewHolder.kt
  app/src/main/res/drawable/ic_history_back.xml
  app/src/main/res/drawable/ic_history_filter.xml
  app/src/main/res/drawable/ic_history_next.xml
  app/src/main/res/drawable/ic_history_search.xml
  app/src/main/res/drawable/ic_history_setting.xml
  app/src/main/res/drawable/shape_yellow0_fill_10_rect.xml
  app/src/main/res/layout/fragment_history.xml
  app/src/main/res/layout/item_history_deposit.xml
  app/src/main/res/layout/item_history_withdraw.xml
  app/src/main/res/values/strings.xml
Labels: 💟 [UI], 🐰 유진

#15 [Feature/#14] API 연결 기초 세팅
  app/build.gradle.kts
  app/src/main/java/com/sopt/kakaobank/data/ApiFactory.kt
Labels: ⚙️ [SETTING]

#18 [Feature/#13] Transfer view API 작업
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/sopt/kakaobank/MainApplication.kt
  app/src/main/java/com/sopt/kakaobank/core/util/KeyStorage.kt
  app/src/main/java/com/sopt/kakaobank/data/ApiFactory.kt
  app/src/main/java/com/sopt/kakaobank/data/api/TransferApiService.kt
  app/src/main/java/com/sopt/kakaobank/data/dto/response/ResponseTransferRecentDto.kt
  app/src/main/java/com/sopt/kakaobank/presentation/transfer/Transfer.kt
  app/src/main/java/com/sopt/kakaobank/presentation/transfer/TransferActivity.kt
  app/src/main/java/com/sopt/kakaobank/presentation/transfer/TransferAdapter.kt
  app/src/main/java/com/sopt/kakaobank/presentation/transfer/TransferViewHolder.kt
  app/src/main/java/com/sopt/kakaobank/presentation/transfer/TransferViewModel.kt
Labels: ⭐ [FEAT], 🐦 언지

#19 [Feature/#16] History view API 작업
  app/src/main/java/com/sopt/kakaobank/core/util/KeyStorage.kt
  app/src/main/java/com/sopt/kakaobank/core/util/context/ContextExt.kt
  app/src/main/java/com/sopt/kakaobank/data/ApiFactory.kt
  app/src/main/java/com/sopt/kakaobank/data/api/HistoryApiService.kt
  app/src/main/java/com/sopt/kakaobank/data/dto/response/History.kt
  app/src/main/java/com/sopt/kakaobank/data/dto/response/ResponseAccountInfoDto.kt
  app/src/main/java/com/sopt/kakaobank/data/dto/response/ResponseMonthPaymentDto.kt
  app/src/main/java/com/sopt/kakaobank/presentation/history/HistoryAdapter.kt
  app/src/main/java/com/sopt/kakaobank/presentation/history/HistoryFragment.kt
  app/src/main/java/com/sopt/kakaobank/presentation/history/HistoryViewHolder.kt
  app/src/main/java/com/sopt/kakaobank/presentation/history/HistoryViewModel.kt
  app/src/main/res/layout/fragment_history.xml
  app/src/main/res/layout/item_history_deposit.xml
  app/src/main/res/layout/item_history_withdraw.xml
Labels: ⭐ [FEAT], 🐰 유진

#20 [Feature/#17] Home view, Transfer view API 작업
  app/src/main/java/com/sopt/kakaobank/core/util/KeyStorage.kt
  app/src/main/java/com/sopt/kakaobank/data/ApiFactory.kt
  app/src/main/java/com/sopt/kakaobank/data/api/HomeApiService.kt
  app/src/main/java/com/sopt/kakaobank/data/api/TransferApiService.kt
  app/src/main/java/com/sopt/kakaobank/data/dto/response/ResponseAccountDto.kt
  app/src/main/java/com/sopt/kakaobank/presentation/home/HomeFragment.kt
  app/src/main/java/com/sopt/kakaobank/presentation/home/HomeItem.kt
  app/src/main/java/com/sopt/kakaobank/presentation/home/HomeItemAdapter.kt
  app/src/main/java/com/sopt/kakaobank/presentation/home/HomeViewModel.kt
  app/src/main/java/com/sopt/kakaobank/presentation/transfer/TransferActivity.kt
  app/src/main/java/com/sopt/kakaobank/presentation/transfer/TransferViewHolder.kt
  app/src/main/java/com/sopt/kakaobank/presentation/transfer/TransferViewModel.kt
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/values/strings.xml
Labels: ⭐ [FEAT], 🐣 윤서

#22 [Feature/#21] transfer binding 수정
  app/src/main/java/com/sopt/kakaobank/presentation/transfer/TransferViewHolder.kt
Labels: ✅ [MOD], 🐦 언지
